# Kubernetes Secret to store sensitive data
# Base64 encoded values (echo -n 'password' | base64)
apiVersion: v1
kind: Secret
metadata:
  name: oracle-secret
  namespace: oracle-spring-app
type: Opaque
data:
  # Replace these with your actual base64 encoded values
  username: c3lzdGVt  # 'system' in base64
  password: b3JhY2xl  # 'oracle' in base64